// Ties each rule pack to its L4. Run after changing a pack, its cases or its .l4:
//
//   node tools/comply4/build.js
//   l4 run tools/comply4/laws/acd-cases.l4
//
// For each pack it writes two files beside the pack:
//
//   <id>-cases.l4   every settled case from <id>-cases.js and every sample, as a Facts record and
//                   one #ASSERT per duty. The expected status is the one the console's engine
//                   computes, so `l4 run` passing means the L4 rules and the console's rules give
//                   the same answer on every stated case.
//   <id>-l4.js      the L4 text of each rule, keyed by name, for the console to show beside a duty.

'use strict';
var fs = require('fs');
var path = require('path');
var C = require('./engine.js');

var TODAY = '2026-10-02';
var LAWS = path.join(__dirname, 'laws');

function tick(name) { return '`' + name + '`'; }

function build(id) {
  var pack = require(path.join(LAWS, id + '.js'));
  var cases = require(path.join(LAWS, id + '-cases.js'));
  var l4Text = fs.readFileSync(path.join(LAWS, id + '.l4'), 'utf8').replace(/\r\n/g, '\n');

  // ---- the L4's rules and fields, by name
  var rules = {}, fields = {};
  l4Text.split(/\n\s*\n/).forEach(function (block) {
    var m = block.match(/^DECIDE `([^`]+)`/m);
    if (m) rules[m[1]] = block.trim();
  });
  var declare = l4Text.match(/DECLARE Facts HAS\n([\s\S]*?)\n\n/);
  var fieldOrder = [];
  declare[1].split('\n').forEach(function (line) {
    var m = line.match(/^\s*`([^`]+)`\s+IS AN? (.+)$/);
    if (m) { fields[m[1]] = m[2].trim(); fieldOrder.push(m[1]); }
  });

  // ---- every name the pack cites must exist in the L4, and every L4 field must be supplied
  var problems = [];
  var factByField = {};
  pack.facts.forEach(function (f) {
    if (!f.l4) return;
    if (!fields[f.l4]) problems.push('fact ' + f.id + ' names an L4 field that is not declared: ' + f.l4);
    factByField[f.l4] = f;
  });
  var derived = {};
  (pack.l4Derived || []).forEach(function (d) {
    if (!fields[d.field]) problems.push('derived field not declared in the L4: ' + d.field);
    derived[d.field] = d.from;
  });
  fieldOrder.forEach(function (name) {
    if (!factByField[name] && !derived[name]) problems.push('L4 field no fact supplies: ' + name);
  });
  pack.duties.forEach(function (d) {
    ['applies', 'met', 'pending'].forEach(function (k) {
      var n = d.l4 && d.l4[k];
      if (k === 'met' && !n) problems.push('duty ' + d.id + ' names no L4 rule');
      if (n && !rules[n] && !fields[n]) problems.push('duty ' + d.id + ' names L4 that does not exist: ' + n);
    });
  });
  if (problems.length) { problems.forEach(function (p) { console.log('  PROBLEM  ' + p); }); process.exit(1); }

  // ---- cases
  function value(name, facts) {
    if (derived[name]) return derived[name](facts) ? 'TRUE' : 'FALSE';
    var f = factByField[name], a = facts[f.id];
    if (f.type === 'bool') return a === true ? 'TRUE' : 'FALSE';
    if (f.type === 'number') return (a === undefined || a === null || a === '') ? '0' : String(Number(a));
    var opt = f.options.filter(function (o) { return o.v === a; })[0] || f.options[f.options.length - 1];
    return tick(opt.l4);
  }
  function term(name, subject) { return fields[name] ? '(' + subject + "'s " + tick(name) + ')' : '(' + tick(name) + ' ' + subject + ')'; }

  var width = fieldOrder.reduce(function (w, n) { return Math.max(w, n.length); }, 0) + 2;
  var samples = {};
  pack.samples.forEach(function (s) { samples[s.id] = s.facts; });

  var all = pack.samples.map(function (s) { return { name: 'Sample: ' + s.name, facts: s.facts }; });
  cases.forEach(function (c) {
    var f = JSON.parse(JSON.stringify(samples[c.from]));
    Object.keys(c.change).forEach(function (k) { if (c.change[k] === undefined) delete f[k]; else f[k] = c.change[k]; });
    all.push({ name: c.name, facts: f });
  });

  var out = [
    'IMPORT ' + tick(id),
    '',
    '-- GENERATED by tools/comply4/build.js from ' + id + '.js and ' + id + '-cases.js. Do not edit.',
    '--',
    '-- Each case is a set of stated facts. Each #ASSERT is the status the console\'s engine gives a',
    '-- duty on those facts, restated against the L4 rules: whether the duty arises, whether it is',
    '-- met, and, where the duty has a time for performance, whether that time has passed.',
    ''
  ];
  var nCases = 0, nAsserts = 0, skipped = [];
  all.forEach(function (c, i) {
    var res = C.assess(pack, c.facts, TODAY);
    if (res.results.some(function (r) { return r.status === 'unknown'; })) { skipped.push(c.name); return; }
    nCases++;
    var subject = tick('case ' + (i + 1));
    out.push('§ ' + tick((i + 1) + ' -- ' + c.name.replace(/`/g, "'")));
    out.push('');
    out.push(subject + ' MEANS Facts WITH');
    fieldOrder.forEach(function (name) {
      out.push('    ' + (tick(name) + new Array(width).join(' ')).slice(0, width + 2) + ' IS ' + value(name, c.facts));
    });
    out.push('');
    res.results.forEach(function (r) {
      var l = r.duty.l4;
      var applies = term(pack.l4Scope, subject) + (l.applies ? ' AND ' + term(l.applies, subject) : '');
      var met = term(l.met, subject);
      var e;
      if (r.status === 'na') e = 'NOT (' + applies + ')';
      else if (r.status === 'met') e = applies + ' AND ' + met;
      else {
        // Each NOT is bracketed with its operand. On one line an unbracketed NOT
        // reaches to the end of the line, so `NOT m AND p` means NOT (m AND p),
        // and L4 now refuses that spelling (l4-ide SET-OPERATORS-SPEC §18.1).
        e = applies + ' AND (NOT ' + met + ')';
        if (l.pending) e += ' AND ' + (r.status === 'due' ? term(l.pending, subject) : '(NOT ' + term(l.pending, subject) + ')');
      }
      out.push('-- ' + r.duty.ref + ' ' + r.duty.title + ': ' + r.status);
      out.push('#ASSERT ' + e);
      nAsserts++;
    });
    out.push('');
  });
  fs.writeFileSync(path.join(LAWS, id + '-cases.l4'), out.join('\n'));

  // ---- the L4 text for the console
  var shown = { rules: {}, fields: {}, file: 'laws/' + id + '.l4', cases: nCases, asserts: nAsserts };
  pack.duties.forEach(function (d) {
    ['applies', 'met', 'pending'].forEach(function (k) {
      var n = d.l4[k];
      if (!n) return;
      if (rules[n]) shown.rules[n] = rules[n]; else shown.fields[n] = fields[n];
    });
  });
  // Rules that the cited rules lean on, so a duty's L4 can be read without the file.
  var grew = true;
  while (grew) {
    grew = false;
    Object.keys(shown.rules).forEach(function (n) {
      Object.keys(rules).forEach(function (other) {
        if (!shown.rules[other] && shown.rules[n].indexOf(tick(other) + ' f') >= 0) { shown.rules[other] = rules[other]; grew = true; }
      });
    });
  }
  shown.rules[pack.l4Scope] = rules[pack.l4Scope];
  Object.keys(rules).forEach(function (other) {
    if (!shown.rules[other] && rules[pack.l4Scope].indexOf(tick(other) + ' f') >= 0) shown.rules[other] = rules[other];
  });
  fs.writeFileSync(path.join(LAWS, id + '-l4.js'),
    '// GENERATED by tools/comply4/build.js from ' + id + '.l4. Do not edit.\n' +
    '(function (root) { (root.Comply4L4 = root.Comply4L4 || {})[' + JSON.stringify(id) + '] = ' +
    JSON.stringify(shown, null, 1) + '; })(typeof self !== \'undefined\' ? self : this);\n');

  console.log(pack.title + ': ' + nCases + ' cases, ' + nAsserts + ' assertions written to laws/' + id + '-cases.l4');
  if (skipped.length) console.log('  ' + skipped.length + ' cases left out because a duty is unsettled in them (the L4 is two-valued)');
}

build('acd');
